version: "3.9"

networks:
  traefik_net:
    external: true
  drupal_internal:
    driver: bridge

volumes:
  drupal_data:
  db_data:

services:
  db:
    image: mariadb:10.11
    container_name: drupal-db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=your_drupal_password
    networks:
      - drupal_internal

  drupal:
    image: drupal:11-php8.3-fpm
    container_name: drupal
    volumes:
      - drupal_data:/var/www/html
    depends_on:
      - db
    networks:
      - drupal_internal
      - traefik_net

  nginx: 
    image: nginx:stable
    container_name: drupal-nginx
    volumes:
      - drupal_data:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - drupal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drupal-http.rule=Host(`chattanooga.digital`) && PathPrefix(`/eduityblog`)"
      - "traefik.http.routers.drupal-http.entrypoints=web"
      - "traefik.http.routers.drupal-http.middlewares=redirect-to-https"
      - "traefik.http.routers.drupal.rule=Host(`chattanooga.digital`) && PathPrefix(`/eduityblog`)"
      - "traefik.http.routers.drupal.entrypoints=websecure"
      - "traefik.http.routers.drupal.tls=true"
      - "traefik.http.routers.drupal.tls.certresolver=letsencrypt"
      - "traefik.http.routers.drupal.middlewares=drupal-stripprefix"
      - "traefik.http.services.drupal.loadbalancer.server.port=80"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.middlewares.drupal-stripprefix.stripprefix.prefixes=/eduityblog"
    networks:
      - drupal_internal
      - traefik_net
