version: "3.9"

services:
  drupal:
    image: drupal:11-fpm
    environment:
      PHP_MEMORY_LIMIT: 512M
    volumes:
      - drupal_data:/var/www/html
    depends_on:
      - db

  nginx: 
    image: nginx:stable
    volumes:
      - drupal_data:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - drupal
    labels:
      - "traefik.enable=true"
      
      # HTTP Router (redirect to HTTPS)
      - "traefik.http.routers.drupal-http.rule=Host(`chattanooga.digital`) && PathPrefix(`/eduityblog`)"
      - "traefik.http.routers.drupal-http.entrypoints=web"
      - "traefik.http.routers.drupal-http.middlewares=redirect-to-https"
      
      # HTTPS Router
      - "traefik.http.routers.drupal.rule=Host(`chattanooga.digital`) && PathPrefix(`/eduityblog`)"
      - "traefik.http.routers.drupal.entrypoints=websecure"
      - "traefik.http.routers.drupal.tls=true"
      - "traefik.http.routers.drupal.tls.certresolver=letsencrypt"
      - "traefik.http.routers.drupal.middlewares=drupal-stripprefix"
      
      # Service
      - "traefik.http.services.drupal.loadbalancer.server.port=80"
      
      # Middlewares
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.middlewares.drupal-stripprefix.stripprefix.prefixes=/eduityblog"
    networks:
      - traefik  # Make sure this network exists

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupalpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  drupal_data:
  db_data:

networks:
  traefik:
    external: true
