version: '3.8'

networks:
  traefik_net:
    external: true
  backend:
    driver: overlay

volumes:
  drupal_data:
  db_data:

configs:
  nginx_conf:
    file: ./nginx.conf
  drupal_settings_local:
    file: ./config/drupal/settings.local.php

services:
  db:
    image: mariadb:10.11
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: your_drupal_password
    networks:
      - backend

  drupal:
    image: drupal:11-php8.3-fpm
    volumes:
      - drupal_data:/var/www/html
    configs:
      - source: drupal_settings_local
        target: /var/www/html/web/sites/default/settings.local.php
        mode: 0444
    networks:
      - backend
      - traefik_net

  nginx:
    image: nginx:stable
    volumes:
      - drupal_data:/var/www/html:ro
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
        mode: 0444
    depends_on:
      - drupal
    networks:
      - backend
      - traefik_net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_net"
        - "traefik.http.routers.eduity-http.rule=Host(`eduity.net`) || Host(`www.eduity.net`)"
        - "traefik.http.routers.eduity-http.entrypoints=web"
        - "traefik.http.routers.eduity-http.middlewares=redirect-to-https"
        - "traefik.http.routers.eduity.rule=Host(`eduity.net`) || Host(`www.eduity.net`)"
        - "traefik.http.routers.eduity.entrypoints=websecure"
        - "traefik.http.routers.eduity.tls=true"
        - "traefik.http.routers.eduity.tls.certresolver=letsencrypt"
        - "traefik.http.services.eduity.loadbalancer.server.port=80"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
